#!/bin/bash
#SBATCH -p grantgpu -A g2025a412g
#SBATCH -N 1
#SBATCH --mem=16G
#SBATCH --constraint="gpua100"
#SBATCH --mail-user="mouhamed.sow@unistra.fr"
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH -o jobs/GTAtoCityscapes_attention.out
hostname
module load python/python-3.8.18
module load cuda/cuda-11.2
source ~/venv/prism-uda/bin/activate
python --version

cd ~/domain_adaptation
python run_experiments.py --config configs/mic/GTAtoCityscapes_attention.py
echo 'END'
